// <auto-generated />
namespace EmpCertDal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class certrenualtimespantodaysvsbug : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(certrenualtimespantodaysvsbug));
        
        string IMigrationMetadata.Id
        {
            get { return "201707021736002_certrenual timespan to days (vs bug)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
